### PR TITLE
Update close function to not throw occasional error

### PR DESCRIPTION
**Pull request by JohnGoodman**
#6

### CODE REVIEW

**Review by wontwon — APPROVED** [review]

**Comment by wontwon** [comment]
Can we get this merged in?

**Comment by generalpaulinski** [comment]
plz merge!

**Comment by kazzkiq** [comment]
@doppelgunner can we have this merged?

**Comment by vyashh** [comment]
I don't think that he updates the source anymore 🙁

**Comment by kazzkiq** [comment]
To future travelers who ends up here, just use [react-media-recorder](https://github.com/0x006F/react-media-recorder/) instead.

**Comment by ravi72munde** [comment]
Anyone who still wish to use with this fix use: https://www.npmjs.com/package/patch-package

**Comment by lorenamelor** [comment]
Please I need this fix. Can you merge?

**Comment by doppelgunner** [comment]
PR was included in this release: v1.0.5:
https://github.com/doppelgunner/audio-react-recorder/releases/tag/v1.0.5

**Pull request merged**
